services:
  - type: web
    name: time-service-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: FLASK_ENV
        value: production
